Modular predictions
ulissigroup/catlas pull request #143
Opened 2022-08-30 21:29 UTC by KirbyBroderick

2022-08-30 21:47 UTC, KirbyBroderick commented
Can we test this with a multi-step inference config file?
Also, what do we think about the docstring for the output of multiple-return functions?

2022-09-01 17:11 UTC, brookwander requested changes
I think it would be nice to bundle up the last step sankey stuff too. Let me know if you want me to take care of that. Otherwise just the one easy fix I mentioned and LGTM

2022-09-01 17:11 UTC, brookwander commented on bin/predictions.py
> +def load_adsorbates_and_filter():
?

2022-09-01 17:11 UTC, brookwander commented on bin/predictions.py
> +def parse_inputs():
I think we should move all of these upfront function definitions to another util file

2022-09-01 17:43 UTC, merged